
setTimeout(function() {
    var img
    img = new Image();
    img.src = "app/Main/resource/imgs/background_nav.png"
    img = new Image();
    img.src = "app/Main/resource/imgs/button_changepwd_hover.png"
    img = new Image();
    img.src = "app/Main/resource/imgs/button_changepwd_normal.png"
    img = new Image();
    img.src = "app/Main/resource/imgs/button_changepwd_pressed.png"
    img = new Image();
    img.src = "app/Main/resource/imgs/button_logout_hover.png"
    img = new Image();
    img.src = "app/Main/resource/imgs/button_logout_normal.png"
    img = new Image();
    img.src = "app/Main/resource/imgs/button_logout_pressed.png"
    img = new Image();
    img.src = "app/Main/resource/imgs/button_nav_00_hover.png"
    img = new Image();
    img.src = "app/Main/resource/imgs/button_nav_00_normal.png"
    img = new Image();
    img.src = "app/Main/resource/imgs/button_nav_00_pressed.png"
    img = new Image();
    img.src = "app/Main/resource/imgs/button_nav_01_hover.png"
    img = new Image();
    img.src = "app/Main/resource/imgs/button_nav_01_normal.png"
    img = new Image();
    img.src = "app/Main/resource/imgs/button_nav_01_pressed.png"
    img = new Image();
    img.src = "app/Main/resource/imgs/button_nav_02_hover.png"
    img = new Image();
    img.src = "app/Main/resource/imgs/button_nav_02_normal.png"
    img = new Image();
    img.src = "app/Main/resource/imgs/button_nav_02_pressed.png"
    img = new Image();
    img.src = "app/Main/resource/imgs/button_nav_03_hover.png"
    img = new Image();
    img.src = "app/Main/resource/imgs/button_nav_03_normal.png"
    img = new Image();
    img.src = "app/Main/resource/imgs/button_nav_03_pressed.png"
    img = new Image();
    img.src = "app/Main/resource/imgs/button_nav_04_hover.png"
    img = new Image();
    img.src = "app/Main/resource/imgs/button_nav_04_normal.png"
    img = new Image();
    img.src = "app/Main/resource/imgs/button_nav_04_pressed.png"
    img = new Image();
    img.src = "app/Main/resource/imgs/button_nav_05_hover.png"
    img = new Image();
    img.src = "app/Main/resource/imgs/button_nav_05_normal.png"
    img = new Image();
    img.src = "app/Main/resource/imgs/button_nav_05_pressed.png"
    img = new Image();
    img.src = "app/Main/resource/imgs/button_nav_06_hover.png"
    img = new Image();
    img.src = "app/Main/resource/imgs/button_nav_06_normal.png"
    img = new Image();
    img.src = "app/Main/resource/imgs/button_nav_06_pressed.png"
    img = new Image();
    img.src = "app/Main/resource/imgs/button_nav_hover.png"
    img = new Image();
    img.src = "app/Main/resource/imgs/button_nav_normal.png"
    img = new Image();
    img.src = "app/Main/resource/imgs/button_nav_pressed.png"
    img = new Image();
    img.src = "app/Main/resource/imgs/button_nav_xxbz_hover.png"
    img = new Image();
    img.src = "app/Main/resource/imgs/button_nav_xxbz_normal.png"
    img = new Image();
    img.src = "app/Main/resource/imgs/button_nav_xxbz_pressed.png"
    img = new Image();
    img.src = "app/Main/resource/imgs/button_updatepwd_hover.png"
    img = new Image();
    img.src = "app/Main/resource/imgs/button_updatepwd_normal.png"
    img = new Image();
    img.src = "app/Main/resource/imgs/button_updatepwd_pressed.png"
    img = new Image();
    img.src = "app/Main/resource/imgs/fxclr1.png"
    img = new Image();
    img.src = "app/Main/resource/imgs/fxclr2.png"
    img = new Image();
    img.src = "app/Main/resource/imgs/fxclr3.png"
    img = new Image();
    img.src = "app/Main/resource/imgs/work_head_background.bmp"
    img = new Image();
    img.src = "app/Main/resource/imgs/work_head_logo.png"
    img = new Image();
    img.src = "app/Main/resource/imgs/zfhc_click.png"
    img = new Image();
    img.src = "app/Main/resource/imgs/zfhc_hot.png"
    img = new Image();
    img.src = "app/Main/resource/imgs/zfhc_normal.png"
    img = new Image();
    img.src = "app/Login/resource/imgs/PKI01.png"
    img = new Image();
    img.src = "app/Login/resource/imgs/PKI02.png"
    img = new Image();
    img.src = "app/Login/resource/imgs/PKI03.png"
    img = new Image();
    img.src = "app/Login/resource/imgs/PKI04.png"
    img = new Image();
    img.src = "app/Login/resource/imgs/bg.png"
    img = new Image();
    img.src = "app/Login/resource/imgs/btn01.png"
    img = new Image();
    img.src = "app/Login/resource/imgs/btn02.png"
    img = new Image();
    img.src = "app/Login/resource/imgs/btn03.png"
    img = new Image();
    img.src = "app/Login/resource/imgs/btn04.png"
    img = new Image();
    img.src = "app/Login/resource/imgs/main.jpg"
    img = new Image();
    img.src = "app/MJWQ/resource/imgs/1111.png"
    img = new Image();
    img.src = "app/MJWQ/resource/imgs/demo.jpg"
    img = new Image();
    img.src = "app/MJWQ/resource/imgs/downloadNormal.png"
    img = new Image();
    img.src = "app/MJWQ/resource/imgs/error.gif"
    img = new Image();
    img.src = "app/MJWQ/resource/imgs/jdkpBtn1.png"
    img = new Image();
    img.src = "app/MJWQ/resource/imgs/jdkpBtn2.png"
    img = new Image();
    img.src = "app/MJWQ/resource/imgs/jdkpBtn3.png"
    img = new Image();
    img.src = "app/MJWQ/resource/imgs/loading.gif"
    img = new Image();
    img.src = "app/MJWQ/resource/imgs/mjwqBtn1.png"
    img = new Image();
    img.src = "app/MJWQ/resource/imgs/mjwqBtn2.png"
    img = new Image();
    img.src = "app/MJWQ/resource/imgs/mjwqBtn3.png"
    img = new Image();
    img.src = "app/MJWQ/resource/imgs/music.gif"
    img = new Image();
    img.src = "app/MJWQ/resource/imgs/otherfile.gif"
    img = new Image();
    img.src = "app/MJWQ/resource/imgs/rcccBtn1.png"
    img = new Image();
    img.src = "app/MJWQ/resource/imgs/rcccBtn2.png"
    img = new Image();
    img.src = "app/MJWQ/resource/imgs/rcccBtn3.png"
    img = new Image();
    img.src = "app/MJWQ/resource/imgs/selectBtn.png"
    img = new Image();
    img.src = "app/MJWQ/resource/imgs/title_page.png"
    img = new Image();
    img.src = "app/MJWQ/resource/imgs/titlebg.png"
    img = new Image();
    img.src = "app/MJWQ/resource/imgs/unselectBtn.png"
    img = new Image();
    img.src = "app/MJWQ/resource/imgs/ycjdBtn1.png"
    img = new Image();
    img.src = "app/MJWQ/resource/imgs/ycjdBtn2.png"
    img = new Image();
    img.src = "app/MJWQ/resource/imgs/ycjdBtn3.png"
    img = new Image();
    img.src = "app/RZSJ/resource/imgs/cjgzzrz_click.png"
    img = new Image();
    img.src = "app/RZSJ/resource/imgs/cjgzzrz_hot.png"
    img = new Image();
    img.src = "app/RZSJ/resource/imgs/cjgzzrz_normal.png"
    img = new Image();
    img.src = "app/RZSJ/resource/imgs/glrzBtn1.png"
    img = new Image();
    img.src = "app/RZSJ/resource/imgs/glrzBtn2.png"
    img = new Image();
    img.src = "app/RZSJ/resource/imgs/glrzBtn3.png"
    img = new Image();
    img.src = "app/RZSJ/resource/imgs/glxtrz_click.png"
    img = new Image();
    img.src = "app/RZSJ/resource/imgs/glxtrz_hot.png"
    img = new Image();
    img.src = "app/RZSJ/resource/imgs/glxtrz_normal.png"
    img = new Image();
    img.src = "app/RZSJ/resource/imgs/log_mgr_nor.png"
    img = new Image();
    img.src = "app/RZSJ/resource/imgs/log_mgr_on.png"
    img = new Image();
    img.src = "app/RZSJ/resource/imgs/log_mgr_sel.png"
    img = new Image();
    img.src = "app/RZSJ/resource/imgs/log_ws_nor.png"
    img = new Image();
    img.src = "app/RZSJ/resource/imgs/log_ws_on.png"
    img = new Image();
    img.src = "app/RZSJ/resource/imgs/log_ws_sel.png"
    img = new Image();
    img.src = "app/RZSJ/resource/imgs/selectBtn.png"
    img = new Image();
    img.src = "app/RZSJ/resource/imgs/titlebg.png"
    img = new Image();
    img.src = "app/RZSJ/resource/imgs/unselectBtn.png"
    img = new Image();
    img.src = "app/RZSJ/resource/imgs/yhrzBtn1.png"
    img = new Image();
    img.src = "app/RZSJ/resource/imgs/yhrzBtn2.png"
    img = new Image();
    img.src = "app/RZSJ/resource/imgs/yhrzBtn3.png"
    img = new Image();
    img.src = "app/RZSJ/resource/imgs/zfjlyrz_click.png"
    img = new Image();
    img.src = "app/RZSJ/resource/imgs/zfjlyrz_hot.png"
    img = new Image();
    img.src = "app/RZSJ/resource/imgs/zfjlyrz_normal.png"
    img = new Image();
    img.src = "app/Share/resource/imgs/IE.png"
    img = new Image();
    img.src = "app/Share/resource/imgs/client_dateselect.png"
    img = new Image();
    img.src = "app/Share/resource/imgs/combobox2_bg_down.png"
    img = new Image();
    img.src = "app/Share/resource/imgs/combobox2_hover_down.png"
    img = new Image();
    img.src = "app/Share/resource/imgs/combobox2_new.png"
    img = new Image();
    img.src = "app/Share/resource/imgs/combobox2_new_hover.png"
    img = new Image();
    img.src = "app/Share/resource/imgs/combobox_new.png"
    img = new Image();
    img.src = "app/Share/resource/imgs/combobox_new_hover.png"
    img = new Image();
    img.src = "app/Share/resource/imgs/date_body.png"
    img = new Image();
    img.src = "app/Share/resource/imgs/date_dropdown.png"
    img = new Image();
    img.src = "app/Share/resource/imgs/delete.png"
    img = new Image();
    img.src = "app/Share/resource/imgs/download.png"
    img = new Image();
    img.src = "app/Share/resource/imgs/edit.png"
    img = new Image();
    img.src = "app/Share/resource/imgs/org_0.png"
    img = new Image();
    img.src = "app/Share/resource/imgs/org_1.png"
    img = new Image();
    img.src = "app/Share/resource/imgs/org_2.png"
    img = new Image();
    img.src = "app/Share/resource/imgs/plugin_download.png"
    img = new Image();
    img.src = "app/Share/resource/imgs/user.png"
    img = new Image();
    img.src = "app/TJFX/resource/imgs/1111.png"
    img = new Image();
    img.src = "app/TJFX/resource/imgs/qsdbt1.png"
    img = new Image();
    img.src = "app/TJFX/resource/imgs/qsdbt2.png"
    img = new Image();
    img.src = "app/TJFX/resource/imgs/qsdbt3.png"
    img = new Image();
    img.src = "app/TJFX/resource/imgs/qst1.png"
    img = new Image();
    img.src = "app/TJFX/resource/imgs/qst2.png"
    img = new Image();
    img.src = "app/TJFX/resource/imgs/qst3.png"
    img = new Image();
    img.src = "app/TJFX/resource/imgs/selectBtn.png"
    img = new Image();
    img.src = "app/TJFX/resource/imgs/titlebg.png"
    img = new Image();
    img.src = "app/TJFX/resource/imgs/tjsj1.png"
    img = new Image();
    img.src = "app/TJFX/resource/imgs/tjsj2.png"
    img = new Image();
    img.src = "app/TJFX/resource/imgs/tjsj3.png"
    img = new Image();
    img.src = "app/TJFX/resource/imgs/unselectBtn.png"
    img = new Image();
    img.src = "app/XTGL/resource/imgs/bmglBtn1.png"
    img = new Image();
    img.src = "app/XTGL/resource/imgs/bmglBtn2.png"
    img = new Image();
    img.src = "app/XTGL/resource/imgs/bmglBtn3.png"
    img = new Image();
    img.src = "app/XTGL/resource/imgs/ccfwqglBtn1.png"
    img = new Image();
    img.src = "app/XTGL/resource/imgs/ccfwqglBtn2.png"
    img = new Image();
    img.src = "app/XTGL/resource/imgs/ccfwqglBtn3.png"
    img = new Image();
    img.src = "app/XTGL/resource/imgs/cjgzzglBtn1.png"
    img = new Image();
    img.src = "app/XTGL/resource/imgs/cjgzzglBtn2.png"
    img = new Image();
    img.src = "app/XTGL/resource/imgs/cjgzzglBtn3.png"
    img = new Image();
    img.src = "app/XTGL/resource/imgs/jsglbtn_click.png"
    img = new Image();
    img.src = "app/XTGL/resource/imgs/jsglbtn_hot.png"
    img = new Image();
    img.src = "app/XTGL/resource/imgs/jsglbtn_normal.png"
    img = new Image();
    img.src = "app/XTGL/resource/imgs/left2.gif"
    img = new Image();
    img.src = "app/XTGL/resource/imgs/right2.gif"
    img = new Image();
    img.src = "app/XTGL/resource/imgs/selectBtn.png"
    img = new Image();
    img.src = "app/XTGL/resource/imgs/titlebg.png"
    img = new Image();
    img.src = "app/XTGL/resource/imgs/unselectBtn.png"
    img = new Image();
    img.src = "app/XTGL/resource/imgs/yhglBtn1.png"
    img = new Image();
    img.src = "app/XTGL/resource/imgs/yhglBtn2.png"
    img = new Image();
    img.src = "app/XTGL/resource/imgs/yhglBtn3.png"
    img = new Image();
    img.src = "app/XTGL/resource/imgs/zfjlyglBtn1.png"
    img = new Image();
    img.src = "app/XTGL/resource/imgs/zfjlyglBtn2.png"
    img = new Image();
    img.src = "app/XTGL/resource/imgs/zfjlyglBtn3.png"
    img = new Image();
    img.src = "app/XTGL/resource/imgs/zxwjglBtn1.png"
    img = new Image();
    img.src = "app/XTGL/resource/imgs/zxwjglBtn2.png"
    img = new Image();
    img.src = "app/XTGL/resource/imgs/zxwjglBtn3.png"
    img = new Image();
    img.src = "app/YJYP/resource/imgs/1.jpg"
    img = new Image();
    img.src = "app/YJYP/resource/imgs/1111.png"
    img = new Image();
    img.src = "app/YJYP/resource/imgs/close.gif"
    img = new Image();
    img.src = "app/YJYP/resource/imgs/red.png"
    img = new Image();
    img.src = "app/YJYP/resource/imgs/selectBtn.png"
    img = new Image();
    img.src = "app/YJYP/resource/imgs/titlebg.png"
    img = new Image();
    img.src = "app/YJYP/resource/imgs/unselectBtn.png"
    img = new Image();
    img.src = "app/YJYP/resource/imgs/warning.png"
    img = new Image();
    img.src = "app/YJYP/resource/imgs/yellow.png"
    img = new Image();
    img.src = "app/YJYP/resource/imgs/yjypBtn1.png"
    img = new Image();
    img.src = "app/YJYP/resource/imgs/yjypBtn2.png"
    img = new Image();
    img.src = "app/YJYP/resource/imgs/yjypBtn3.png"
    img = new Image();
    img.src = "app/YJYP/resource/imgs/yjypmsgBtn1.png"
    img = new Image();
    img.src = "app/YJYP/resource/imgs/yjypmsgBtn2.png"
    img = new Image();
    img.src = "app/YJYP/resource/imgs/yjypmsgBtn3.png"
    img = new Image();
    img.src = "app/YJYP/resource/imgs/yjypnianBtn1.png"
    img = new Image();
    img.src = "app/YJYP/resource/imgs/yjypnianBtn2.png"
    img = new Image();
    img.src = "app/YJYP/resource/imgs/yjypnianBtn3.png"
    img = new Image();
    img.src = "app/YJYP/resource/imgs/yjypquBtn1.png"
    img = new Image();
    img.src = "app/YJYP/resource/imgs/yjypquBtn2.png"
    img = new Image();
    img.src = "app/YJYP/resource/imgs/yjypquBtn3.png"
    img = new Image();
    img.src = "app/YJYP/resource/imgs/yjypyueBtn1.png"
    img = new Image();
    img.src = "app/YJYP/resource/imgs/yjypyueBtn2.png"
    img = new Image();
    img.src = "app/YJYP/resource/imgs/yjypyueBtn3.png"
    img = new Image();
    img.src = "app/YJYP/resource/imgs/yjypzhBtn1.png"
    img = new Image();
    img.src = "app/YJYP/resource/imgs/yjypzhBtn2.png"
    img = new Image();
    img.src = "app/YJYP/resource/imgs/yjypzhBtn3.png"
    img = new Image();
    img.src = "app/ZFJD/resource/imgs/1111.png"
    img = new Image();
    img.src = "app/ZFJD/resource/imgs/bjxx1.png"
    img = new Image();
    img.src = "app/ZFJD/resource/imgs/bjxx2.png"
    img = new Image();
    img.src = "app/ZFJD/resource/imgs/bjxx3.png"
    img = new Image();
    img.src = "app/ZFJD/resource/imgs/demo.jpg"
    img = new Image();
    img.src = "app/ZFJD/resource/imgs/downloadNormal.png"
    img = new Image();
    img.src = "app/ZFJD/resource/imgs/error.gif"
    img = new Image();
    img.src = "app/ZFJD/resource/imgs/jdkpBtn1.png"
    img = new Image();
    img.src = "app/ZFJD/resource/imgs/jdkpBtn2.png"
    img = new Image();
    img.src = "app/ZFJD/resource/imgs/jdkpBtn3.png"
    img = new Image();
    img.src = "app/ZFJD/resource/imgs/loading.gif"
    img = new Image();
    img.src = "app/ZFJD/resource/imgs/music.gif"
    img = new Image();
    img.src = "app/ZFJD/resource/imgs/otherfile.gif"
    img = new Image();
    img.src = "app/ZFJD/resource/imgs/rcccBtn1.png"
    img = new Image();
    img.src = "app/ZFJD/resource/imgs/rcccBtn2.png"
    img = new Image();
    img.src = "app/ZFJD/resource/imgs/rcccBtn3.png"
    img = new Image();
    img.src = "app/ZFJD/resource/imgs/selectBtn.png"
    img = new Image();
    img.src = "app/ZFJD/resource/imgs/title_page.png"
    img = new Image();
    img.src = "app/ZFJD/resource/imgs/titlebg.png"
    img = new Image();
    img.src = "app/ZFJD/resource/imgs/unselectBtn.png"
    img = new Image();
    img.src = "app/ZFJD/resource/imgs/xpxx1.png"
    img = new Image();
    img.src = "app/ZFJD/resource/imgs/xpxx2.png"
    img = new Image();
    img.src = "app/ZFJD/resource/imgs/xpxx3.png"
    img = new Image();
    img.src = "app/ZFJD/resource/imgs/ycjdBtn1.png"
    img = new Image();
    img.src = "app/ZFJD/resource/imgs/ycjdBtn2.png"
    img = new Image();
    img.src = "app/ZFJD/resource/imgs/ycjdBtn3.png"
}, 1000);
