/**
 * Created by hcxowe on 14-2-21.
 */
Ext.define('TJFX.model.QSDBTChartModel', {
    extend: 'Ext.data.Model',
    fields: [
        {name: 'DATE',      type: "string"},
        {name: 'data1',     type: "int"},
        {name: 'data2',     type: "int"},
        {name: 'data3',     type: "int"},
        {name: 'data4',     type: "int"},
        {name: 'data5',     type: "int"},
        {name: 'data6',     type: "int"},
        {name: 'data7',     type: "int"},
        {name: 'data8',     type: "int"},
        {name: 'data9',     type: "int"},
        {name: 'data10',    type: "int"},
        {name: 'data11',    type: "int"},
        {name: 'data12',    type: "int"},
        {name: 'data13',    type: "int"},
        {name: 'data14',    type: "int"},
        {name: 'data15',    type: "int"},
        {name: 'data16',    type: "int"},
        {name: 'data17',    type: "int"},
        {name: 'data18',    type: "int"},
        {name: 'data19',    type: "int"},
        {name: 'data20',    type: "int"},
        {name: 'data21',    type: "int"},
        {name: 'data22',    type: "int"},
        {name: 'data23',    type: "int"},
        {name: 'data24',    type: "int"},
        {name: 'data25',    type: "int"},
        {name: 'data26',    type: "int"},
        {name: 'data27',    type: "int"},
        {name: 'data28',    type: "int"},
        {name: 'data29',    type: "int"},
        {name: 'data30',    type: "int"},
        {name: 'data31',    type: "int"},
        {name: 'data32',    type: "int"},
        {name: 'data33',    type: "int"},
        {name: 'data34',    type: "int"},
        {name: 'data35',    type: "int"},
        {name: 'data36',    type: "int"},
        {name: 'data37',    type: "int"},
        {name: 'data38',    type: "int"},
        {name: 'data39',    type: "int"},
        {name: 'data40',    type: "int"},
        {name: 'data41',    type: "int"},
        {name: 'data42',    type: "int"},
        {name: 'data43',    type: "int"},
        {name: 'data44',    type: "int"},
        {name: 'data45',    type: "int"},
        {name: 'data46',    type: "int"},
        {name: 'data47',    type: "int"},
        {name: 'data48',    type: "int"},
        {name: 'data49',    type: "int"},
        {name: 'data50',    type: "int"}
    ]
});